/**
 * Builds the per-route <head> contents.
 *
 * Used by the prerenderer to bake tags into static HTML, and by App.tsx to
 * keep them correct after client-side navigation. One implementation so the
 * two can't drift — the previous drift (a static title in index.html and a
 * different one set by JS) made the homepage title visibly change on hydrate.
 */

import {
  SITE_NAME,
  SITE_ORIGIN,
  SITEWIDE_JSONLD,
  canonicalFor,
  type RouteMeta,
} from '../routes';

/**
 * A real 1200x630 card, generated by scripts/optimize-images.ts.
 *
 * This used to be logo.png, a 327x329 square. Every platform expecting a
 * 1.91:1 card letterboxed or cropped it, and twitter:card was pinned to
 * "summary" (the small square layout) because a square in a large-card slot
 * looks broken. Dimensions are declared below so a crawler can lay the card
 * out before the image finishes downloading.
 */
const OG_IMAGE = `${SITE_ORIGIN}/og-card.png`;
const OG_IMAGE_WIDTH = '1200';
const OG_IMAGE_HEIGHT = '630';

function escapeAttr(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * JSON-LD is injected inside a <script> block, so `<` must be neutralised or a
 * value containing "</script>" would break out of it.
 */
function escapeJsonLd(json: string): string {
  return json.replace(/</g, '\\u003c');
}

export interface HeadTag {
  /** How the client finds the existing element to update. */
  selector: string;
  html: string;
}

/** Ordered tags for a route, as both selectors (client) and HTML (prerender). */
export function buildHeadTags(route: RouteMeta): HeadTag[] {
  const canonical = canonicalFor(route.path);
  const title = escapeAttr(route.title);
  const description = escapeAttr(route.description);

  const tags: HeadTag[] = [
    { selector: 'title', html: `<title>${title}</title>` },
    {
      selector: 'meta[name="description"]',
      html: `<meta name="description" content="${description}" />`,
    },
    {
      selector: 'link[rel="canonical"]',
      html: `<link rel="canonical" href="${canonical}" />`,
    },
    { selector: 'meta[property="og:type"]', html: `<meta property="og:type" content="website" />` },
    {
      selector: 'meta[property="og:site_name"]',
      html: `<meta property="og:site_name" content="${SITE_NAME}" />`,
    },
    {
      selector: 'meta[property="og:title"]',
      html: `<meta property="og:title" content="${title}" />`,
    },
    {
      selector: 'meta[property="og:description"]',
      html: `<meta property="og:description" content="${description}" />`,
    },
    { selector: 'meta[property="og:url"]', html: `<meta property="og:url" content="${canonical}" />` },
    {
      selector: 'meta[property="og:image"]',
      html: `<meta property="og:image" content="${OG_IMAGE}" />`,
    },
    {
      selector: 'meta[property="og:image:width"]',
      html: `<meta property="og:image:width" content="${OG_IMAGE_WIDTH}" />`,
    },
    {
      selector: 'meta[property="og:image:height"]',
      html: `<meta property="og:image:height" content="${OG_IMAGE_HEIGHT}" />`,
    },
    {
      selector: 'meta[property="og:image:alt"]',
      html: `<meta property="og:image:alt" content="${escapeAttr(SITE_NAME)} — get found on Google and in AI answers" />`,
    },
    {
      selector: 'meta[property="og:locale"]',
      html: `<meta property="og:locale" content="en_US" />`,
    },
    {
      selector: 'meta[name="twitter:card"]',
      html: `<meta name="twitter:card" content="summary_large_image" />`,
    },
    {
      selector: 'meta[name="twitter:title"]',
      html: `<meta name="twitter:title" content="${title}" />`,
    },
    {
      selector: 'meta[name="twitter:description"]',
      html: `<meta name="twitter:description" content="${description}" />`,
    },
    {
      selector: 'meta[name="twitter:image"]',
      html: `<meta name="twitter:image" content="${OG_IMAGE}" />`,
    },
  ];

  if (route.noindex) {
    tags.push({
      selector: 'meta[name="robots"]',
      html: `<meta name="robots" content="noindex, follow" />`,
    });
  }

  const graph = [...SITEWIDE_JSONLD, ...(route.jsonLd ?? [])];
  const json = JSON.stringify({ '@context': 'https://schema.org', '@graph': graph });
  tags.push({
    selector: 'script[type="application/ld+json"]',
    html: `<script type="application/ld+json">${escapeJsonLd(json)}</script>`,
  });

  return tags;
}

/** Flattened HTML for the prerenderer to splice into <head>. */
export function renderHeadHtml(route: RouteMeta): string {
  return buildHeadTags(route)
    .map((t) => `    ${t.html}`)
    .join('\n');
}
